[[redirects]]
  from = "/homecoming"
  to = "https://walkertonhomecoming.netlify.app"
  status = 200
  force = true

[[redirects]]
  from = "/homecoming/*"
  to = "https://walkertonhomecoming.netlify.app/:splat"
  status = 200
  force = true
