[[redirects]]
  from = "/homecoming"
  to = "https://walkertonhomecoming.jdsstudio.ca"
  status = 200
  force = true

[[redirects]]
  from = "/homecoming/*"
  to = "https://walkertonhomecoming.jdsstudio.ca/:splat"
  status = 200
  force = true
